# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  max_anlagen:  10
  max_zims:  10
  start_date: 2000
  end_date: 2050
