# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

anlage:
  class:   sfDoctrineRouteCollection
  options: { model: Anlage }

zim:
  class:   sfDoctrineRouteCollection
  options: { model: Zim }

zim_export:
  url:     /zim/:id/export
  class:   sfDoctrineRoute
  options: { model: Zim, type: object }
  param:   { module: zim, action: export }
  requirements:
    id: \d+
    sf_method: [get]

zim_delete_stunde:
  url:     /zim/:id/delete_stunde
  class:   sfDoctrineRoute
  options: { model: Zim, type: object }
  param:   { module: zim, action: deleteStunde }
  requirements:
    id: \d+
    sf_method: [delete]

bild:
  class:   sfDoctrineRouteCollection
  options: { model: Bild }

stunde:
  class:   sfDoctrineRouteCollection
  options: { model: Stunde }

anlage_search:
  url:   /search
  param: { module: anlage, action: search }

anlage_export:
  url:     /anlage/:id/export
  class:   sfDoctrineRoute
  options: { model: Anlage, type: object }
  param:   { module: anlage, action: export }
  requirements:
    id: \d+
    sf_method: [get]

anlage_remove_stunde:
  url:     /anlage/:id/removeStunde
  class:   sfDoctrineRoute
  options: { model: Anlage, type: object }
  param:   { module: anlage, action: removeStunde }
  requirements:
    id: \d+
    sf_method: [get]

change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# default rules
homepage:
  url:   /
  param: { module: anlage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

