# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

anlage:
  class:   sfDoctrineRouteCollection
  options: { model: Anlage }

zim:
  class:   sfDoctrineRouteCollection
  options: { model: Zim }

zim_export:
  url:     /zim/:id/export
  class:   sfDoctrineRoute
  options: { model: Zim, type: object }
  param:   { module: zim, action: export }
  requirements:
    id: \d+
    sf_method: [get]

zim_export_preview:
  url:     /zim/:id/export_preview
  class:   sfDoctrineRoute
  options: { model: Zim, type: object }
  param:   { module: zim, action: exportPreview }
  requirements:
    id: \d+
    sf_method: [get]

zim_delete_stunde:
  url:     /zim/:id/delete_stunde
  class:   sfDoctrineRoute
  options: { model: Zim, type: object }
  param:   { module: zim, action: deleteStunde }
  requirements:
    id: \d+
    sf_method: [get]

bild:
  class:   sfDoctrineRouteCollection
  options: { model: Bild }

stunde:
  class:   sfDoctrineRouteCollection
  options: { model: Stunde }

anlage_search:
  url:   /search
  param: { module: anlage, action: search }

anlage_export:
  url:     /anlage/:id/export
  class:   sfDoctrineRoute
  options: { model: Anlage, type: object }
  param:   { module: anlage, action: export }
  requirements:
    id: \d+
    sf_method: [get]

anlage_export_preview:
  url:     /anlage/:id/export_preview
  class:   sfDoctrineRoute
  options: { model: Anlage, type: object }
  param:   { module: anlage, action: exportPreview }
  requirements:
    id: \d+
    sf_method: [get]

anhang_download:
  url:     /anhang/:id/download
  class:   sfDoctrineRoute
  options: { model: Anhang, type: object }
  param:   { module: anhang, action: download }
  requirements:
    id: \d+
    sf_method: [get]

anlage_remove_stunde:
  url:     /anlage/:id/removeStunde
  class:   sfDoctrineRoute
  options: { model: Anlage, type: object }
  param:   { module: anlage, action: removeStunde }
  requirements:
    id: \d+
    sf_method: [get]

anlage_remove_section:
  url:     /anlage/:id/removeSection
  class:   sfDoctrineRoute
  options: { model: Section, type: object }
  param:   { module: anlage, action: removeSection }
  requirements:
    id: \d+
    sf_method: [get]
    
anlage_add_section:
  url:     /anlage/:id/addSection
  class:   sfDoctrineRoute
  options: { model: Anlage, type: object }
  param:   { module: anlage, action: addSection }
  requirements:
    id: \d+
    sf_method: [get]
    
change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }

sf_guard_user_new:
  url: /sfGuardUser/new
  param: { module: sfGuardUser, action: new }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

admin_tools:
  url:   /tools
  param: {module: tools, action: index }

admin_tools_download:
  url:  /download
  param: {module: tools, action: download }

# default rules
homepage:
  url:   /
  param: { module: anlage, action: index }

